# Generated by Django 5.2.9 on 2025-12-21 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='available',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='student_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_time',
            field=models.DateTimeField(default='2025-12-25 10:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.destination'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
